//import ArrowDown from "../../../assets/images/dashboard/dropdownChart.svg";
import ChartComponent from '../components/ChartCompoent'

const LineChart = () => {
  return (
    <div
      className="h-[410px] p-5 bg-[#FFFFFF] rounded-xl"
      style={{
        boxShadow: "0px 4px 30px 0px #2E2D740D",
        width: "calc(100% - 312px)",
      }}
    >
      <div className="flex justify-between items-center w-full">
        <p className="text-[#22173D] text-2xl font-semibold">
          Revenue Generated
        </p>
        <button className="text-[#883DCF] bg-[#FAF5FF] rounded-[4px] px-3 py-1 flex items-center gap-1 font-semibold text-2xl">
          Monthly
         
        </button>
      </div>
      <div className="flex justify-between items-center w-full mt-3">
        <p className="text-[#858D9D] font-normal">
          Total revenue generated by the customers
        </p>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1">
            <div className="w-[12px] h-[12px] rounded-full bg-[#9854FF]" />
            <p className="text-[#64748B] font-normal text-xs">Enterprise</p>
          </div>
          <div className="items">
            <div className="w-[12px] h-[12px] rounded-full bg-[#00DDEB]" />
            <p className="text-[#64748B] font-normal text-xs">Individuals</p>
          </div>
        </div>
      </div>
      <ChartComponent />
    </div>
  );
};

export default LineChart;